FROM mcr.microsoft.com/dotnet/sdk:7.0-alpine

ENV ASPNETCORE_URLS http://*:5181

WORKDIR /app

COPY . .

# Compile the dotnet application during build-stage of docker image, rather than during runtime.
RUN dotnet publish -o .

CMD ["./api-dotnet"]